#!/usr/bin/env bash
SCRIPTPATH="$( cd -- "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 ; pwd -P )"
pluginspath="$(mame -showconfig | grep pluginspath | sed 's/^pluginspath \+//g')"
mame c64 -window -plugins -pluginspath "${pluginspath};${SCRIPTPATH}/mameplugins" -plugin mamelink &
export MAMELINK="${SCRIPTPATH}/mameplugins/mamelink"
./down < reno.out
